### PR TITLE
Added streaming services as protos to nDPI

### PR DESCRIPTION
**Pull request by ChrisNelson-CyberReef**
* Apple TV+
* DirecTV
* HBO
* Vudu
* Showtime
* Dailymotion
* Livestream
* Tencent Video
* IHeart Radio
* Tidal
* TuneIn
* SiriusXM Radio

Domains based on https://www.netify.ai/resources/applications

### CODE REVIEW

**Comment by IvanNardi** [comment]
Regardless of what @vel21ripn will do with this PR here, might I backport it upstream?

**Comment by ChrisNelson-CyberReef** [comment]
> Regardless of what @vel21ripn will do with this PR here, might I backport it upstream?

Yes, please.

**Comment by vel21ripn** [comment]
If this PR appears in the main branch, then I will make a backport.

**Comment by IvanNardi** [comment]
Ok, I'll merge it on upstream asap, giving proper credit to @ChrisNelson-CyberReef

**Comment by IvanNardi** [comment]
Done in 3d0c36cf2223f59da165d429b91fbfe5b40db987

**Comment by vel21ripn** [comment]
I updated my fork to the current state of the 'dev' branch.

**Pull request closed without merging**
